### ISSUE TITLE
Support all ~200 caDSR CDE datatypes

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-cadsr-tools#6]
We currently support the 10 most common caDSR CDE datatypes (CHARACTER, NUMBER, java.lang.String, DATE, java.lang.Long, java.lang.Integer, java.lang.Double, java.util.Date, ALPHANUMERIC, ISO21090CDv1.0). 

We do not support the remaining ~190. Some are pretty obscure (e.g., ISO21090TELURLv1.0, ISO21090.TEL.URL.v1.0, ISO21090BLv1.0) and are used in only a few CDEs. However, we cannot handle ~10% of caDSR CDEs due to not handling these types.

Supporting some of these datatypes may be non trivial if we assume that we also validate that supplied values conform to the specified datatype.

**Comment by martinjoconnor** [comment]
As per Denise, they would likely map most of the 'odd' datatypes to more standard datatypes - so we'd likely have a far smaller set to deal with.

**Comment by marcosmro** [comment]
We have updated our transformation tool to handle all the remaining CDEs, except for those CDEs:
1. with status different from RELEASED.
2. with Date-time and Time datatypes. We plan to handle them in the next few months.
3. with a short list of datatypes that we agreed to ignore because they are not relevant.

Here is a summary of the results obtained after running the transformation on Dec 11, 2019 (for CDEs downloaded on Nov 4, 2019):
- Number of input caDSR CDEs: 66,787
- Number of CEDAR CDEs generated: 58,557 (87.68%)
- Number of CEDAR CDEs skipped: 8,230 (12.32%)
  - Non-released status: 7569
  - Date-time and Time: 653
  - Ignored: 8
